import { ArrowLeft } from 'lucide-react'
import type { BlogPost } from '../data/blog.generated'
import { posts } from '../data/blog.generated'
import { formatPostDate } from '../lib/blog'

/**
 * /blog/:slug — a single post.
 *
 * `html` is rendered from Contentful rich text at BUILD time
 * (scripts/fetch-contentful.mjs), which keeps the Contentful renderer out of
 * the client bundle entirely. The markup is produced by our own renderer from
 * our own CMS, so the injection is a controlled, first-party string.
 */
export function BlogPostPage({ post }: { post: BlogPost }) {
  const more = posts.filter((p) => p.slug !== post.slug).slice(0, 3)

  return (
    <>
      <article className="section pt-0">
        <div className="shell pt-[calc(var(--nav-h)+clamp(28px,5vw,56px))]">
          <nav aria-label="Breadcrumb" className="mx-auto max-w-[46rem] text-[0.82rem] font-600 text-ink-faint">
            <ol className="flex flex-wrap items-center gap-1.5">
              <li><a href="/" className="transition-colors hover:text-ink">Home</a></li>
              <li aria-hidden>/</li>
              <li><a href="/blog" className="transition-colors hover:text-ink">Blog</a></li>
            </ol>
          </nav>

          <div className="mx-auto mt-6 max-w-[46rem]">
            <p className="text-[0.72rem] font-800 uppercase tracking-[0.08em] text-accent-deep">
              {post.tags[0] ?? 'Article'}
            </p>
            <h1 className="t-h2 mt-3">{post.title}</h1>
            <p className="mt-4 flex flex-wrap items-center gap-x-2 gap-y-1 text-[0.88rem] font-600 text-ink-faint">
              {post.authorAvatar && (
                <img
                  src={`${post.authorAvatar}?w=64&h=64&fit=thumb&f=face&fm=webp`}
                  alt=""
                  width={28}
                  height={28}
                  className="size-7 rounded-full object-cover"
                />
              )}
              <span className="text-ink-soft">{post.author}</span>
              <span aria-hidden>·</span>
              <time dateTime={post.publishedDate}>{formatPostDate(post.publishedDate)}</time>
              <span aria-hidden>·</span>
              <span>{post.readingMinutes} min read</span>
            </p>
          </div>

          {post.image && (
            <img
              src={`${post.image}?w=1600&h=900&fit=fill&fm=webp&q=78`}
              alt={post.imageAlt}
              width={1600}
              height={900}
              className="mx-auto mt-8 aspect-[16/9] w-full max-w-[52rem] rounded-card border border-line object-cover"
            />
          )}

          {/* eslint-disable-next-line react/no-danger -- first-party CMS HTML,
              generated by our own renderer at build time (see module docs) */}
          <div
            className="mx-auto mt-10 max-w-[46rem] text-[1.02rem]"
            dangerouslySetInnerHTML={{ __html: post.html }}
          />

          <p className="mx-auto mt-12 max-w-[46rem]">
            <a href="/blog" className="inline-flex items-center gap-1.5 text-[0.95rem] font-700 text-ink-soft transition-colors hover:text-ink">
              <ArrowLeft className="size-4" /> All posts
            </a>
          </p>
        </div>
      </article>

      {more.length > 0 && (
        <section className="section bg-surface/40 pt-0">
          <div className="shell">
            <h2 className="t-h3">Keep reading</h2>
            <div className="mt-6 grid gap-4 md:grid-cols-3">
              {more.map((p) => (
                <a
                  key={p.slug}
                  href={`/blog/${p.slug}`}
                  className="group flex flex-col rounded-card border border-line bg-surface p-5 shadow-sm transition-colors hover:border-accent/40"
                >
                  <h3 className="font-display text-[1.02rem] font-800 leading-snug tracking-[-0.01em] group-hover:text-accent-deep">
                    {p.title}
                  </h3>
                  <p className="mt-2 line-clamp-2 text-[0.9rem] leading-relaxed text-ink-soft">
                    {p.description}
                  </p>
                  <p className="mt-auto pt-4 text-[0.8rem] font-600 text-ink-faint">
                    {formatPostDate(p.publishedDate)}
                  </p>
                </a>
              ))}
            </div>
          </div>
        </section>
      )}
    </>
  )
}
