// GENERATED by scripts/fetch-contentful.mjs — do not edit by hand.
// Regenerated on every build; committed so builds work without credentials.
export type BlogPost = {
  id: string
  slug: string
  title: string
  description: string
  publishedDate: string
  updatedAt: string
  author: string
  authorAvatar: string | null
  image: string | null
  imageAlt: string
  tags: string[]
  readingMinutes: number
  seoTitle: string | null
  seoDescription: string | null
  noindex: boolean
  /** Rich text pre-rendered to HTML at build time. */
  html: string
}

export const posts: BlogPost[] = []
